# Generated by Django 4.2.6 on 2026-02-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_cancel_notified',
            field=models.BooleanField(default=False, verbose_name='自動キャンセル通知済み'),
        ),
    ]
