# Generated by Django 4.2.6 on 2026-01-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='notification',
        ),
    ]
