# Generated by Django 4.2.6 on 2026-01-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_notified',
            field=models.BooleanField(default=False, verbose_name='期限切れ通知済み'),
        ),
    ]
