# Generated by Django 4.2.6 on 2026-02-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='locker_number',
            field=models.IntegerField(blank=True, help_text='QRから取得したロッカー番号', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='locker_pin',
            field=models.CharField(blank=True, help_text='店舗が設定した暗証番号', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '準備待ち'), ('ready', '準備完了'), ('completed', '受け取り完了'), ('canceled', 'キャンセル')], default='pending', max_length=10),
        ),
    ]
