# Generated by Django 4.2.6 on 2026-02-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_locker_number_order_locker_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='locker_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='locker_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
